List<String> DetoxUtils = [
  "Begin your detox journey today. Unplug from all social media platforms for 24 hours.",
  "Explore a new hobby or activity that doesn't involve screens.",
  "Audit your digital life. Unfollow or unfriend accounts that no longer inspire or serve you.",
  "Designate specific times for checking emails and messages to reduce screen time.",
  "Create a technology-free zone in your home.",
  "Write down your thoughts and feelings about your digital detox experience.",
  "Spend quality time with loved ones, in-person or via a call.",
  "Reflect on the positive changes you've noticed since starting the detox.",
  "Practice mindfulness for 15 minutes. Focus on your breath and the present moment.",
  "Limit screen time to only essential tasks today.",
  "Read a physical book or magazine instead of digital content.",
  "Engage in a creative project or craft away from screens.",
  "Write down your personal goals for the next year.",
  "Disconnect from screens at least one hour before bedtime.",
  "Explore a digital minimalism practice. Identify apps or platforms you can permanently reduce or eliminate.",
  "Unsubscribe from email lists that clutter your inbox.",
  "Practice a 30-minute digital detox daily—no screens allowed.",
  "Engage in a digital-free outdoor activity.",
  "Conduct a digital detox review. Reflect on the impact of this challenge on your life.",
  "Create a plan for maintaining a healthy tech-life balance moving forward.",
  "Celebrate your successful detox journey. Embrace your newfound digital freedom!"
];
