List<String> JournalUtil = [
  "Start your journaling journey today. Write about your goals and intentions for this challenge.",
  "Reflect on your morning routine. What can you do to make your mornings more productive?",
  "Describe one thing you're grateful for and why.",
  "Write about a challenge you're facing and possible solutions.",
  "Share a personal success story or achievement.",
  "Document your daily routine, hour by hour.",
  "Write a letter to your future self, expressing your hopes and aspirations.",
  "List three things you love about yourself.",
  "Describe a recent book, movie, or experience that made an impact on you.",
  "Share your favorite motivational quote and explain why it inspires you.",
  "Write about a difficult decision you've made and the reasons behind it.",
  "Document a recent act of kindness, either given or received.",
  "Reflect on a moment when you felt truly happy.",
  "Write a letter of forgiveness, either to yourself or someone else.",
  "Describe a place you've always wanted to visit and why.",
  "Share a lesson you've learned from a recent mistake.",
  "Document your daily thoughts and feelings in a stream of consciousness.",
  "Write about a person who has influenced your life in a positive way.",
  "Describe your ideal day from start to finish.",
  "Share a personal growth goal and your plan to achieve it.",
  "Celebrate your journaling journey. Reflect on the insights and self-discoveries you've gained.",
];
