List<String> MeditationUtils = [
  "Start Slow\n5 minutes Meditation\nFocus on your breath",
  "5 minutes Meditation\nTake Slow Breath",
  "5 minutes Meditation",
  "5 minutes Meditation\nThink of someone you love",
  "5 minutes Meditation\ngo some natural peaceful place",
  "5 minutes Meditation\nTry concentration meditaton by focusing on one object for 5 minutes\n (Candle,tree,etc)",
  "5 minutes Meditation\nList three things you are grateful for",
  "Increase duration\n10 minutes Meditation",
  "10 minutes Meditation\nSay 5 Positive things about yourself",
  "10 minutes Meditation\nList three things you are grateful for",
  "10 minutes Meditation",
  "10 minutes Meditation\nList three amazing things happened today",
  "10 minutes Meditation",
  "10 minutes Meditation\nVisualize a place you love",
  "10 minutes Meditation\nList three things you are grateful for",
  "10 minutes Meditation\n ake deep breaths outside",
  "10 minutes Meditation",
  "10 minutes Meditation\nSay three compliments to yourself",
  "10 minutes Meditation\nList three things that happened today",
  "10 minutes Meditation\nList five persons you love",
  "Increase duration\n 15 minutes Meditation",
];
