List<String> NoJunkUtils = [
  "Define Your Why: \nThink about why you want to quit junk food and write down your reasons",
  "Kitchen Clean-Up: \nRemove all junk food items from your kitchen",
  "Healthy Grocery Shopping: \nCreate a shopping list of nutritious foods and go grocery shopping",
  "Meal Planning: \nPlan your meals for the week ahead",
  "Portion Control: \nLearn about appropriate portion sizes",
  "Healthy Snack Alternatives: \nResearch and prepare a list of healthy snacks",
  "Mindful Eating: \nPractice eating mindfully",
  "Identify Triggers: \nStart identifying triggers for your junk food cravings",
  "Stress Management: \nLearn and practice stress-reduction techniques",
  "Hydration: \nEnsure you're staying hydrated by drinking enough water",
  "Social Support: \nShare your goal with friends or family members",
  "Positive Affirmations: \nCreate positive affirmations related to avoiding junk food",
  "Plan for Cravings: \nDevelop strategies for handling cravings",
  "Celebrate Small Wins: \nCelebrate your achievements in the first two weeks",
  "Check-In with Your Why: \nReflect on your initial reasons for quitting junk food",
  "Meal Variety: \nExperiment with new healthy recipes",
  "Physical Activity: \nIncorporate regular exercise into your routine",
  "Positive Visualization: \nVisualize a healthier, junk-free version of yourself",
  "Self-Compassion: \nBe compassionate with yourself if you slip up",
  "Encourage Others: \nShare your experiences and inspire others",
  "Reflect and Celebrate: \nReflect on your journey and celebrate your success",
];
